### ISSUE TITLE
一阶龙格库塔与构建增量四元数相乘有什么区别吗

### ISSUE THREAD

**Issue by exat500g** [Hom-Wang/SmartIMU#6]
比如我现在的代码是这样的
quaternion delta;
delta.w = 1;
delta.x = (gyro.x) * dt / 2;
delta.y = (gyro.y) * dt / 2;
delta.z = (gyro.z) * dt / 2;
quaternion left=earthToBodyQuaternion;
quaternion_mult(&earthToBodyQuaternion,&left,&delta);
quaternion_normalize(&earthToBodyQuaternion);
实际使用并没有什么问题

**Comment by Hom-Wang** [comment]
@exat500g 不太懂你說的＂一階龍格庫塔與構建增量四元數相乘＂的意思

基本的四元數更新是透過角度來更新，使用龍格－庫塔方法，主要是讓四元數可以直接透過角速度來更新（其實一階的龍格－庫塔就是差分的意思），因為目前使用的領域是用來計算載具的姿態角，陀螺儀僅能輸出角速度，所以才需要用角速度更新四元數的方法，詳細可以參考這篇→[四元數](https://github.com/Hom-Wang/Quadcopter/blob/master/%E6%8E%A8%E5%B0%8E_%E5%9B%9B%E5%85%83%E6%95%B8.pdf)。

**Comment by exat500g** [comment]
看过了,将我上面的四元数乘法展开后得到的公式是和一阶龙格库塔法一样的,但是多了一些计算量.

**Comment by Hom-Wang** [comment]
了解你的意思了，基本上結果是一樣的，

．角度更新
一個四元數 QA 表示當下角度，另一四元數 QB 表示旋轉角度，更新後的四元數 Q = QA x QB
QB 是 QB(theta, phi, psi)，需要知道角度。

．角速度更新
透過龍格－庫塔方法，讓 QB 變成 QB[t+1] = QB[t] + deltaT/2 * matrixW，之後一樣透過 Q = QA x QB 來旋轉，需要知道角速度。

所以只差別只在於是用角度更新 QB 還是用角速度更新 QB 的差別而已，
要證明其是否相同只須證明 QB(theta, phi, psi) 與 QB[t+1] = QB[t] + deltaT/2 * matrixW 相同即可，
其實多的計算量就是龍格－庫塔的計算量，為的就是使用角速度更新 QB。

**Comment by exat500g** [comment]
实际上我的所谓增量四元数就是由龍格庫塔法得来的
Qdelta = (dt/2)*[1 gx gy gz]'
Q[t+1] = Q[t]xQdelta
结果和
Q[t+1] = Q[t] + deltaT/2 * matrixW  是一样的
还是龍格庫塔法更能揭示陀螺仪积分的本质

**Comment by Hom-Wang** [comment]
1. Qdelta = (dt/2)*[1 gx gy gz]'
    應該是 Qdelta = (dt/2)*[2/dt gx gy gz]' 才是符合你一開始的設定。

2. 如果兩者是相等的（依你的結果而論），我覺得是因為旋轉角度很小導致的特例情況，
    由四元數 P2 可知，四元數表示式 Q = q0 + q1*i + q2*j + q3*k = cos[theta/2] + n * sin[theta/2]，
    當 theta/2 很小時，Q ~ 1 + n * theta/2，
    令 w 為角速度，上式可以整理成 Q ~ 1 + (w * n) * (deltaT / 2)，
    也就是你說的 Qdelta = [1　gx * (dt/2)　gy * (dt/2)　gz * (dt/2)]'，
    僅提出這種猜想，沒有仔細的驗證過，正確與否可能需要你自己去確認。

**Comment by exat500g** [comment]
matlab验证代码:
%runge-kutta
dt = 1.0;
gx = 3.14159;
gy = 0.0;
gz = 0;

q0=1;
q1=0;
q2=0;
q3=0;

qDot1 = 0.5*(-q1 * gx- q2 * gy - q3 * gz);
qDot2 = 0.5*(q0 * gx + q2 * gz - q3 * gy);
qDot3 = 0.5*(q0 * gy - q1 * gz + q3 * gx);
qDot4 = 0.5*(q0 * gz + q1 * gy - q2 * gx);

q=[q0 q1 q2 q3];
qd=[qDot1 qDot2 qDot3 qDot4];

q=q+qd*dt;

q

%quat_mult
q=[1 0 0 0];
qd=[1 dt*0.5*gx dt*0.5*gy dt*0.5*gz];

q=quatmultiply(q,qd);
q

结果证明两者是一样的
角速度大的情況对于龙格库塔也是一样的,毕竟是一阶差分

**Comment by Hom-Wang** [comment]
剛將 qd = [1 dt*0.5*gx dt*0.5*gy dt*0.5*gz] 帶入乘法運算後（四元數P2 乘法關係），
代數的形式確實是與龍格－庫塔的結果一樣（四元數P5的龍格－庫塔），無關旋轉角度大小與否。

不過讓我納悶的是 qd = [1 dt*0.5*gx dt*0.5*gy dt*0.5*gz] 這個關係，
這意味著一個四元數 qd = [ 1　theta/2　phi/2　psi/2 ] 在任何情況下都成立，感覺並不合理。
