### ISSUE TITLE
板子是怎么画出这种效果的

### ISSUE THREAD

**Issue by TimorRunnnnnn** [Hom-Wang/SmartIMU#7]
我们都表示板子画的漂亮啊...
难道是用矩形块手动画的吗?

**Comment by Hom-Wang** [comment]
用 solid region 手動畫的，一開始本來想說試看看效果，
但畫到一半覺得很麻煩，刪掉又覺得很可惜，所以就硬著頭皮畫完了...

**Comment by TimorRunnnnnn** [comment]
厉害厉害,请问你mpu9250和ms5611怎么焊接的...我现在是在焊盘上刷锡,然后放到回流焊炉过一遍,但是这样mpu9250在下沉以后和板子不水平..

**Comment by Hom-Wang** [comment]
MPU9250 之前是用熱風槍吹的，方法詳細可以看 [Youtube](https://youtu.be/Ln0jjqr-quY)
不過之後買了新的銲槍搭配 HAKKO T12-KU 的細刀頭後，可以直接用焊槍焊。

MS5611 一直都是用焊槍焊的，這個難度較低。
