### ISSUE TITLE
Slave0及Slave4的差別

### ISSUE THREAD

**Issue by ijunglee** [Hom-Wang/SmartIMU#8]
您好，我最近在進行用MSP430透過SPI讀取數個MPU9250的專案，我請教了invensense官方，他們提供的initial flow如下：

![code](https://cloud.githubusercontent.com/assets/12967717/15491713/dee04f38-21a5-11e6-9ed8-0ea5d0207669.PNG)

這邊控制磁力計的部分都是對I2C_SLV0做設定，讀取也是從I2C_SLV0讀，但是我發現參照這個initial flow偶爾會發生磁力計ID讀取不到(應該要是0x48，但是讀取出來為0x00)，導致磁力計資料整個都是0的問題。加速規及陀螺儀的值則是一直都讀得到，沒有問題。

我發現您在這邊是對Slave 0及Slave 4做設定，想請教您這兩者的差別？先前有寫信給美國invensense，他們的答覆也是建議我使用Slave 4，但是不太清楚這幾個Register的差別？
以及若使用Slave 4是否適用在SPI讀取多顆MPU9250的情況？
謝謝您！=)

依蓉

**Comment by Hom-Wang** [comment]
Hi 依蓉,

關於 slv0 & slv4 的差別可以參考 [mpu9250 datasheet](http://www.invensense.com/products/motion-tracking/9-axis/mpu-9250/)＂4.14 MPU-9250 Solution Using SPI Interface＂

![mpu9250_spi_slvx](https://cloud.githubusercontent.com/assets/4789358/15498807/9ff86c78-21d3-11e6-97e4-b1e4ed1181c3.png)

就自己的實驗與理解，對於 single byte 的讀寫 slv4 較為合適，像是設定 mpu9250 裡的磁力計暫存器或是讀取 device id 之類的，對於重複讀取資料則是以 slv0~3 較合適，依所設定的 i2c 資訊與地址，自動器讀取磁力計的暫存器。

所以我是先透過 slv4 [(this)](https://github.com/Hom-Wang/SmartIMU/blob/master/Software/SmartIMU_TestHardware/Program/modules/module_mpu9250.c#L128) 來設定磁力計、讀取 id 以及相關的校正參數，這部分只需要做一次，再設定 slv0 ([this](https://github.com/Hom-Wang/SmartIMU/blob/master/Software/SmartIMU_TestHardware/Program/modules/module_mpu9250.c#L389))來自動讀取磁力計的資料暫存器與狀態暫存器，最後只需要跟加速度與角速度一起讀出即可。

下面是讀取 mpu9250 九軸資料的實現 [source code](https://github.com/Hom-Wang/SmartIMU/blob/master/Software/SmartIMU_TestHardware/Program/modules/module_mpu9250.c#L446)，因為 slv0~3 會透過 i2c 自動將從磁力計的資料讀取並存至暫存器 EXT_SENS_DATA_xx 裡，所以只須從該暫存器讀出，並判斷磁力計數據是否轉換完成（磁力計部分可參考 ak8963 datasheet）

![getdata](https://cloud.githubusercontent.com/assets/4789358/15501509/65baf6ea-21e0-11e6-8ae1-139865594fec.png)

另外關於 spi 讀取多顆 mpu9250 的部分，不同的 mpu9250 會接在相同的 sck, sdo, sdi 上，透過不同的 cs 來選擇要讀寫哪個 mpu9250，每個都是獨立去設定 slv0~4，不同的 mpu9250 間並不互相衝突。

**Comment by ijunglee** [comment]
謝謝您的回答，請問SPI讀取磁力計資料的程式是指[這支](https://github.com/Hom-Wang/SmartIMU/blob/master/Software/SmartIMU_TestHardware/Program/modules/module_imu.c)嗎？

我參考了您的流程實作後的程式碼如[this](http://pastebin.com/dEqm2jiR)，大致上的流程就是先做完InitialSensor之後，就直接進入ReadAll，num參數均為sensor編號，這邊只用一顆所以均設定為初始值0。

結果發現有以下兩個問題：

1. line 178的
if(!(!(response[14] & AK8963_STATUS_DRDY) || (response[14] & AK8963_STATUS_DOR) || (response[21] & AK8963_STATUS_HOFL)))
response為我去讀取ACC~MAG資料的結果，會存在這個buffer內
這段我一直判斷出false，所以無法取得磁力計的資料
我抓了response的結果如下：
![problem](https://cloud.githubusercontent.com/assets/12967717/15533529/99f49efe-2297-11e6-947c-d522e5b19fa2.PNG)

2. 不只磁力計，加速規和陀螺儀我讀出來的資料也非常不穩定：
![problem2](https://cloud.githubusercontent.com/assets/12967717/15533591/e3961a88-2297-11e6-9ea5-b21f2ff43214.PNG)

以上資料均為MPU9250平放時的結果
請問您有看出什麼樣的問題嗎？謝謝您！

**Comment by Hom-Wang** [comment]
關於你的兩個問題：

1、直判斷出 false 的情況有可能是因為沒有設定好 slv0 的自動讀取或是磁力計的設定，可以在寫完後，再讀出來確認是否有正確寫入，另外是我比較你和我寫的，發現初始化的 clock source 不同，不知道有沒有差，有點懶得看 datasheet...，還有 delay 的部分（[this](http://pastebin.com/dEqm2jiR) line 140），速度太快會導致 i2c 還沒有寫完就被中斷掉了，延遲部分感覺問題比較大。

有試過讀取磁力計的 device id 還有之前的問題嗎？

2、磁力計的讀寫應該是影響不到陀螺儀和加速度計的，需要先確定是否在傳輸的部分有問題，可以先關閉 slv0 的自動讀取，再讀看看加速度計和陀螺儀是否還有相同問題。 

因為手邊也沒有相同的硬體，很難幫忙除錯，只能比較自己寫的，
另外可以試試從感測器上拉出 AUX_CL 和 AUX_DA 的腳位，勾在示波器上，
確定 i2c 可以自動讀寫，以及時脈是否有錯誤。
